import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className="bg-golden-500 p-4 text-black">
        <div className="container mx-auto flex justify-between items-center">
          <div className="text-2xl font-semibold"> 
          <Link href="/">
          <Image
              src="/logo.png"
              alt="Vercel Logo"
              className="border rounded-full w-24 h-24"
              width={80}
              height={8}
              priority
            /></Link></div>
          <nav>
            <ul className="flex space-x-6">
              <li>
                <Link href="/blogs">Blogs</Link>
              </li>
              <li>
                <Link href="/articles">Articles</Link>
              </li>
              <li>
                {/* <Link href="/articles">Articles</Link> */}Login/Signup
              </li>
            </ul>
          </nav>
        </div>
      </header>
      <main className="container mx-auto p-4">{children}</main>
      <footer className="bg-blue-500 p-4 text-white">
        <div className="container mx-auto flex justify-between">
          <div className="text-sm">&copy; 2023 Your Company</div>
        </div>
      </footer>
    </body>
      
    </html>
  )
}
